# Generated by Django 5.0.7 on 2024-08-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
