# Generated by Django 5.0.7 on 2024-08-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
