# Generated by Django 5.0.7 on 2024-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_hash_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_buyable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
